# Generated by Django 5.0.1 on 2024-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
